import { crc16 } from "../crc16";

describe("crc16 - CRC16-Modbus", () => {
  describe("canonical vectors from firmware verification", () => {
    // These vectors were generated by executing firmware CRC16::Calculate()
    // and verified against actual transmission. See: shared/docs/protocol/test_vectors/

    it("Vector 001 - Minimum Valid Packet", () => {
      // Input: 55AA01100000 (empty payload)
      const data = new Uint8Array([0x55, 0xAA, 0x01, 0x10, 0x00, 0x00]);
      const result = crc16(data);

      // Firmware output: 0x4E1F
      expect(result).toBe(0x4E1F);
      expect(result).toBe(19999); // decimal equivalent
    });

    it("Vector 002 - Typical Relay Set Command", () => {
      // Input: 55AA0210000201 (RELAY_SET command, relay 0, state ON)
      const data = new Uint8Array([0x55, 0xAA, 0x02, 0x10, 0x00, 0x02, 0x00, 0x01]);
      const result = crc16(data);

      // Firmware output: 0x6E3D
      expect(result).toBe(0x6E3D);
      expect(result).toBe(28221); // decimal equivalent
    });

    it("Vector 003 - Maximum Payload Packet", () => {
      // Input: Header + Seq + Cmd + Len + 256-byte incrementing payload
      const data = new Uint8Array(262);
      data[0] = 0x55;
      data[1] = 0xAA;
      data[2] = 0x03;
      data[3] = 0x20;
      data[4] = 0x01;
      data[5] = 0x00;
      for (let i = 0; i < 256; i++) {
        data[6 + i] = i & 0xFF;
      }

      const result = crc16(data);

      // Firmware output: 0x4B85
      expect(result).toBe(0x4B85);
      expect(result).toBe(19333); // decimal equivalent
    });

    it("Vector 004 - Random/Complex Payload", () => {
      // Input: Diverse payload pattern
      const data = new Uint8Array([
        0x55, 0xAA, 0x04, 0x60, 0x00, 0x10,
        0x55, 0xAA, 0x55, 0xAA, 0xAA, 0x55,
        0x44, 0x01, 0xFF, 0x80, 0x00, 0xCC, 0x33,
      ]);

      const result = crc16(data);

      // Firmware output: 0x29C2
      expect(result).toBe(0x29C2);
      expect(result).toBe(10690); // decimal equivalent
    });

    it("Vector 005 - CRC Failure Case (correct CRC calculation)", () => {
      // Input: Same as Vector 002 but with different sequence number
      const data = new Uint8Array([0x55, 0xAA, 0x05, 0x10, 0x00, 0x02, 0x00, 0x01]);
      const result = crc16(data);

      // Firmware output: 0x5E1D (correct CRC; test transmits 0xFFFF for error detection)
      expect(result).toBe(0x5E1D);
      expect(result).toBe(24093); // decimal equivalent
    });
  });

  describe("input validation", () => {
    it("should throw on null data", () => {
      expect(() => crc16(null as any)).toThrow(TypeError);
    });

    it("should throw on undefined data", () => {
      expect(() => crc16(undefined as any)).toThrow(TypeError);
    });

    it("should throw on non-Uint8Array data", () => {
      expect(() => crc16([0x01, 0x02] as any)).toThrow(TypeError);
    });

    it("should throw on string data", () => {
      expect(() => crc16("hello" as any)).toThrow(TypeError);
    });

    it("should throw on invalid initialValue (negative)", () => {
      expect(() => crc16(new Uint8Array([0x01]), -1)).toThrow(RangeError);
    });

    it("should throw on invalid initialValue (too large)", () => {
      expect(() => crc16(new Uint8Array([0x01]), 0x10000)).toThrow(RangeError);
    });

    it("should throw on non-numeric initialValue", () => {
      expect(() => crc16(new Uint8Array([0x01]), "0xffff" as any)).toThrow(RangeError);
    });
  });

  describe("determinism", () => {
    it("should be deterministic - same input produces same output", () => {
      const data = new Uint8Array([0x01, 0x02, 0x03, 0x04, 0x05]);
      const result1 = crc16(data);
      const result2 = crc16(data);
      expect(result1).toBe(result2);
    });

    it("should produce same result across multiple calls", () => {
      const data = new Uint8Array([0xaa, 0xbb, 0xcc, 0xdd]);
      const crc1 = crc16(data);
      const crc2 = crc16(data);
      const crc3 = crc16(data);
      expect(crc1).toBe(crc2);
      expect(crc2).toBe(crc3);
    });
  });

  describe("edge cases", () => {
    it("should handle empty buffer", () => {
      const result = crc16(new Uint8Array([]));
      // Empty buffer with 0xFFFF initial returns 0xFFFF (after XOR 0x0000)
      expect(result).toBe(0xffff);
    });

    it("should handle single byte 0x00", () => {
      const result = crc16(new Uint8Array([0x00]));
      expect(typeof result).toBe("number");
      expect(result).toBeGreaterThanOrEqual(0);
      expect(result).toBeLessThanOrEqual(0xffff);
    });

    it("should handle single byte 0xFF", () => {
      const result = crc16(new Uint8Array([0xff]));
      expect(typeof result).toBe("number");
      expect(result).toBeGreaterThanOrEqual(0);
      expect(result).toBeLessThanOrEqual(0xffff);
    });

    it("should handle all zeros", () => {
      const data = new Uint8Array(10).fill(0x00);
      const result = crc16(data);
      expect(result).toBeGreaterThanOrEqual(0);
      expect(result).toBeLessThanOrEqual(0xffff);
    });

    it("should handle all ones", () => {
      const data = new Uint8Array(10).fill(0xff);
      const result = crc16(data);
      expect(result).toBeGreaterThanOrEqual(0);
      expect(result).toBeLessThanOrEqual(0xffff);
    });

    it("should handle frame header pattern (0x55 0xAA)", () => {
      const data = new Uint8Array([0x55, 0xaa]);
      const result = crc16(data);
      expect(result).toBeGreaterThanOrEqual(0);
      expect(result).toBeLessThanOrEqual(0xffff);
    });

    it("should handle alternating pattern", () => {
      const data = new Uint8Array([0xaa, 0x55, 0xaa, 0x55, 0xaa, 0x55]);
      const result = crc16(data);
      expect(result).toBeGreaterThanOrEqual(0);
      expect(result).toBeLessThanOrEqual(0xffff);
    });
  });

  describe("incremental calculation", () => {
    it("should support incremental CRC calculation", () => {
      const part1 = new Uint8Array([0x01, 0x02]);
      const part2 = new Uint8Array([0x03, 0x04]);
      const combined = new Uint8Array([0x01, 0x02, 0x03, 0x04]);

      // Incremental: calculate part1, then part2 with part1's CRC as initialValue
      const crcPart1 = crc16(part1);
      const crcIncremental = crc16(part2, crcPart1);

      // All at once
      const crcCombined = crc16(combined);

      expect(crcIncremental).toBe(crcCombined);
    });

    it("should support multi-part incremental calculation", () => {
      const part1 = new Uint8Array([0x01]);
      const part2 = new Uint8Array([0x02]);
      const part3 = new Uint8Array([0x03]);
      const combined = new Uint8Array([0x01, 0x02, 0x03]);

      let crc = crc16(part1);
      crc = crc16(part2, crc);
      crc = crc16(part3, crc);
      const crcCombined = crc16(combined);

      expect(crc).toBe(crcCombined);
    });

    it("should handle long data as single vs incremental", () => {
      const data = new Uint8Array(100);
      for (let i = 0; i < 100; i++) {
        data[i] = i & 0xff;
      }

      // Calculate all at once
      const crcAll = crc16(data);

      // Calculate incrementally in 10-byte chunks
      let crcIncremental = crc16(data.slice(0, 10));
      for (let i = 10; i < 100; i += 10) {
        crcIncremental = crc16(data.slice(i, i + 10), crcIncremental);
      }

      expect(crcIncremental).toBe(crcAll);
    });
  });

  describe("return value properties", () => {
    it("should always return a number", () => {
      const testCases = [
        new Uint8Array([]),
        new Uint8Array([0x00]),
        new Uint8Array([0xff]),
        new Uint8Array([0x55, 0xaa, 0x01, 0x10, 0x00, 0x02, 0x01, 0x01]),
      ];

      testCases.forEach((data) => {
        const result = crc16(data);
        expect(typeof result).toBe("number");
        expect(Number.isFinite(result)).toBe(true);
      });
    });

    it("should always return integer", () => {
      const testCases = [
        new Uint8Array([0x01]),
        new Uint8Array([0x01, 0x02, 0x03]),
        new Uint8Array(50).fill(0xaa),
      ];

      testCases.forEach((data) => {
        const result = crc16(data);
        expect(Number.isInteger(result)).toBe(true);
      });
    });

    it("should return value in 16-bit unsigned range", () => {
      const testCases = [
        new Uint8Array([0x00]),
        new Uint8Array([0xff]),
        new Uint8Array([0x00, 0x00, 0x00, 0x00]),
        new Uint8Array([0xff, 0xff, 0xff, 0xff]),
      ];

      testCases.forEach((data) => {
        const result = crc16(data);
        expect(result >= 0 && result <= 65535).toBe(true);
      });
    });
  });

  describe("large buffer handling", () => {
    it("should handle 256-byte buffer", () => {
      const data = new Uint8Array(256);
      for (let i = 0; i < 256; i++) {
        data[i] = i & 0xff;
      }
      const result = crc16(data);
      expect(result).toBeGreaterThanOrEqual(0);
      expect(result).toBeLessThanOrEqual(0xffff);
    });

    it("should handle 1000-byte buffer", () => {
      const data = new Uint8Array(1000);
      for (let i = 0; i < 1000; i++) {
        data[i] = (i * 7) & 0xff; // Pseudo-random pattern
      }
      const result = crc16(data);
      expect(result).toBeGreaterThanOrEqual(0);
      expect(result).toBeLessThanOrEqual(0xffff);
    });

    it("should handle maximum protocol payload (256 bytes data)", () => {
      // Per PROTOCOL_SPEC.md, maximum payload is 256 bytes
      const data = new Uint8Array(262); // 6 header bytes + 256 payload
      data[0] = 0x55;
      data[1] = 0xAA;
      data[2] = 0x01;
      data[3] = 0x20;
      data[4] = 0x01;
      data[5] = 0x00;
      for (let i = 0; i < 256; i++) {
        data[6 + i] = i & 0xff;
      }
      const result = crc16(data);
      expect(result).toBeGreaterThanOrEqual(0);
      expect(result).toBeLessThanOrEqual(0xffff);
    });
  });

  describe("protocol specification compliance", () => {
    it("should match firmware parameter: Polynomial 0xA001", () => {
      // The polynomial is baked into the algorithm
      // All test vectors passing verifies correct polynomial
      const vectors = [
        { data: new Uint8Array([0x55, 0xAA, 0x01, 0x10, 0x00, 0x00]), expected: 0x4E1F },
        { data: new Uint8Array([0x55, 0xAA, 0x02, 0x10, 0x00, 0x02, 0x00, 0x01]), expected: 0x6E3D },
      ];

      vectors.forEach((vector) => {
        expect(crc16(vector.data)).toBe(vector.expected);
      });
    });

    it("should match firmware parameter: Initial Value 0xFFFF", () => {
      // Empty buffer returns 0xFFFF (XORed with 0x0000)
      const result = crc16(new Uint8Array([]));
      expect(result).toBe(0xFFFF);
    });

    it("should match firmware parameter: Input Reflection Yes (LSB first)", () => {
      // Reflected form processes LSB first; verified by canonical vectors
      const data = new Uint8Array([0x55, 0xAA, 0x01, 0x10, 0x00, 0x00]);
      const result = crc16(data);
      expect(result).toBe(0x4E1F); // Only true if using reflected form
    });

    it("should match firmware parameter: Output Reflection Yes (LSB first)", () => {
      // Output reflection is handled by algorithm; verified by canonical vectors
      const data = new Uint8Array([0x55, 0xAA, 0x02, 0x10, 0x00, 0x02, 0x00, 0x01]);
      const result = crc16(data);
      expect(result).toBe(0x6E3D);
    });

    it("should match firmware parameter: Final XOR 0x0000", () => {
      // Final XOR with 0x0000 means no change; result is used as-is
      // All vectors produce values in valid range (0-65535)
      const testData = [
        new Uint8Array([0x55, 0xAA, 0x01, 0x10, 0x00, 0x00]),
        new Uint8Array([0x55, 0xAA, 0x02, 0x10, 0x00, 0x02, 0x00, 0x01]),
      ];

      testData.forEach((data) => {
        const result = crc16(data);
        expect(result).toBeGreaterThanOrEqual(0);
        expect(result).toBeLessThanOrEqual(0xffff);
      });
    });
  });

  describe("interoperability", () => {
    it("should produce identical output to firmware for canonical vector 1", () => {
      const data = new Uint8Array([0x55, 0xAA, 0x01, 0x10, 0x00, 0x00]);
      expect(crc16(data)).toBe(0x4E1F);
    });

    it("should produce identical output to firmware for canonical vector 2", () => {
      const data = new Uint8Array([0x55, 0xAA, 0x02, 0x10, 0x00, 0x02, 0x00, 0x01]);
      expect(crc16(data)).toBe(0x6E3D);
    });

    it("should produce identical output to firmware for canonical vector 3", () => {
      const data = new Uint8Array(262);
      data[0] = 0x55;
      data[1] = 0xAA;
      data[2] = 0x03;
      data[3] = 0x20;
      data[4] = 0x01;
      data[5] = 0x00;
      for (let i = 0; i < 256; i++) {
        data[6 + i] = i & 0xFF;
      }
      expect(crc16(data)).toBe(0x4B85);
    });

    it("should produce identical output to firmware for canonical vector 4", () => {
      const data = new Uint8Array([
        0x55, 0xAA, 0x04, 0x60, 0x00, 0x10,
        0x55, 0xAA, 0x55, 0xAA, 0xAA, 0x55,
        0x44, 0x01, 0xFF, 0x80, 0x00, 0xCC, 0x33,
      ]);
      expect(crc16(data)).toBe(0x29C2);
    });

    it("should produce identical output to firmware for canonical vector 5", () => {
      const data = new Uint8Array([0x55, 0xAA, 0x05, 0x10, 0x00, 0x02, 0x00, 0x01]);
      expect(crc16(data)).toBe(0x5E1D);
    });
  });
});
